# Site
name: "i am gini"
title: "Gini"
description: "backpacker, foodie, techie"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

url: "https://www.iamgini.com/devops-playground"
baseurl: "/devops-playground"

# If you are building a GitHub project page then use these settings:
# url: "https://www.iamgini.com/site2/"
# baseurl: "/site2"

google_analytics: 'UA-158250524-1'
#disqus: 'demowebsite'
#disqus: 'iamginicom'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  gini:
    name: Gini
    display_name: Gini Gangadharan 
    avatar: 'assets/images/avatar.png'
    gravatar: 1558aaf0c06196e6b9cb24c21e5ca858
    email: net.gini@gmail.com
    web: https://www.iamgini.com
    twitter: https://twitter.com/ginigangadharan
    description: "Backpacker, Foodie, Techie"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-1676785078101005"
adsense-data-ad-slot: "2394512673"  # ad-slot-iamgini-101

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
